name: Hello World

on: [push]

jobs:
  Print-Hello-World:
    runs-on: ubuntu-latest
    steps:
      - run: echo Hello word
      - name: Check o repositorio
        uses: actions/checkout@v3
      - run: echo ok....
